### ISSUE TITLE
Plugin wont work at all

### ISSUE THREAD

**Issue by TimeLessHD** [SirZontax/RPGChat#10]
**Describe the bug**
Plugin wont work at all

**To Reproduce**
1. Put in the Plugins folder 
2. Join the Game nothing works
3. See error = No Error

**Expected behavior**
![9dc91a2b542122f0f76723233debe440](https://user-images.githubusercontent.com/25706356/148378692-bda78987-8a31-44c4-8356-2a8c7c01d287.png)

**Screenshots or Logs (Use https://hastebin.com/ for Logs or the Code Formatting)**

**Server (please complete the following information):**
 - 1.16.5
 - Premium

**Additional context**
None

**Comment by SirZontax** [comment]
Hey, I tested it with the newest version of Spigot-1.16.5 and it worked fine, are you sure there is no plugin with a similar function or an error code?

**Comment by TimeLessHD** [comment]
Oh, damn yeah I just solved the problem I had Bungeechat (Another Chat System) installed. Thanks eitherway mate ^^

**Comment by SirZontax** [comment]
Okay, no problem
