### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by kaisenlmao** [SirZontax/RPGChat#12]
**Describe the bug**
Plugin won't load at all

**To Reproduce**
1. Install the plugin '...'
2. See error

https://www.toptal.com/developers/hastebin/utakajawek.csharp)

**Server (please complete the following information):**
 - Version: [Pufferfish 1.17.1]
 - API-Type: [Spigot]
 - ChatManager

**Comment by SirZontax** [comment]
Hey, does this happen even in the newest Plugin Version?

**Comment by SirZontax** [comment]
Because of no answers, closed.
