### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by BlahaiLama** [SirZontax/RPGChat#13]
Hello, I have issues with the plugin. It doesnt display the written message. Technically yes, it displays, but its jibberish.
Attaching screenshot...
My server is running on 1.18.
![2022-03-27_16 07 56](https://user-images.githubusercontent.com/76487864/160285581-a571c2ca-db04-4682-a567-347ff939649c.png)
1

**Comment by SirZontax** [comment]
Hello, I tested it myself but I can't reproduce your bug.

Did you change something from the default Configuration? Is there maybe any other plugin which has interaction with the Chat or ArmorStands?
