### ISSUE TITLE
Auto-Correct

### ISSUE THREAD

**Issue by Cheu3172** [SirZontax/RPGChat#15]
You should add a configuration that automatically corrects errors such as messages going on top of each other. It should check once per set time by the user in the configuration.

**Comment by SirZontax** [comment]
Hey, 

could you specify what you mean by that, please?

**Comment by Cheu3172** [comment]
When a player chats to fast the RPG-Bubbles (For Text) start to stack-up on each other and it becomes annoying, so what should be used is either a wait function that allows the previous text to complete before showing what the player said after that or a automatic clear function where it clears the previous RPG-Bubble (For Text) once the player sends a new message.
