### ISSUE TITLE
Not working 1.19.2

### ISSUE THREAD

**Issue by anbetender** [SirZontax/RPGChat#18]
**Describe the bug**
Text isnt showen at all, not over the head how it should be. I just downloaded the .jar file and putted it into my plugins folder. Do I have to do "more"? 

**Expected behavior**
Text over the head :D

**Screenshots or Logs (Use https://hastebin.com/ for Logs or the Code Formatting!)**
If applicable, add screenshots or logs to help explain your problem.

**Server (please complete the following information):**
 - Version: 1.19.2
 - API-Type: Spigot
 - Plugins with similar or same function: none

**Comment by SirZontax** [comment]
Hey, if you got multiple worlds, maybe check if you whitelisted the world inside your config.yml. 

To say more, I need to know if there are any errors in the logs and if you are using any other plugins which inteferer with the Chat.
