### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by mohdomari** [SirZontax/RPGChat#2]
**Describe the bug**
'I've installed the plugin and attempted many commands, restarts reloads, etc... But it hasn't worked at all.

**To Reproduce**
1. Do 'Installed the plugin in the plugin folders'
2. Click on 'N/a'
4. See error 'N/a'

**Expected behavior**
For the plugin to work as told, have the chat above the player's head.
**Screenshots or Logs (Use https://hastebin.com/ for Logs or the Code Formatting)**
If applicable, add screenshots or logs to help explain your problem.
N/a
**Server (please complete the following information):**
 - Version [e.g. 1.16.4]
 - 1.17
 - Plugins with similar or same function
 - N/a

**Additional context**

**Comment by SirZontax** [comment]
Hey,

is there a Error Message in the console? Besides, did you use the newest version from the website and the correct jar file?

**Comment by mohdomari** [comment]
No errors in console and I downloaded the latest version from SpigotMC

**Comment by SirZontax** [comment]
Did you enabled it in the config? Was the config even created? You just downloaded it from Spigot and put it in your plugins folder of your spigot server, right?

**Comment by mohdomari** [comment]
Yes, I've downloaded it and put it in the folder. I did not know that I had to enable it, so that is my bad. Would you mind tell me how to enable it exactly as I viewed the config file even before contacting you but it wasn't clear to me that I had to enable it or how to enable it. I apologize in advance if my issue was any sort of annoyance.

**Comment by SirZontax** [comment]
No, it's my fault. I saw right now there is no variable to enable it (thought it was because of another project I'm working on), so sorry for this. Your Issue is no annoyance, that's why this section exists. But as you stated, there is indeed the config file, I wonder if you could contact me via Discord to look further into it.

**Comment by mohdomari** [comment]
Yes sure my discord is Omari#1105

**Comment by SirZontax** [comment]
Fixed:
- World name was not listed inside the config under worlds
