### ISSUE TITLE
Plugin Crashes upon sending Whisper Message

### ISSUE THREAD

**Issue by DontStarve72** [SirZontax/RPGChat#6]
**Describe the bug**

**To Reproduce**
1. Send a Whisper message prepended with a '#'
2. Observe as the message sends in base chat as well as not appearing above the player's head
3. See error

**Expected behavior**
Functioning whisper messages

**Screenshots or Logs (Use https://hastebin.com/ for Logs or the Code Formatting)**
https://hastebin.com/coyahukeni.csharp

**Server (please complete the following information):**
 - 1.17.1 (Purpur version git-Purpur-1393)

**Comment by SirZontax** [comment]
Fixed with 1.6.1-BETA
